### ISSUE TITLE
[feat] 공통된 예외/응답 처리, 인증 이메일, 회원가입, 로그인 

### ISSUE THREAD

**Issue by heyazoo1007** [heyazoo1007/accountbook#1]
## 📌  Feature Issue

프로젝트 초반 틀 설정
* 공통된 예외처리
* 공통된 api 응답을 위한 ApiResponse 
* 사용자 회원가입
* 로그인 구현 

## 📝  To-do

- [x] 예외처리 클래스(ControllerExceptionHandler, ErrorCode 등) 구현
- [x] ApiResponse 클래스 구현
- [x] 이메일 중복 확인 
- [x] 인증 이메일 전송 
- [x] 사용자 회원가입 
- [x] JWT 토큰 이용한 로그인 구현 
- [x] 서비스 테스트
