### ISSUE TITLE
[feat] 한달/1년 총 지출내역 카테고리별로 조회하는 기능 구현

### ISSUE THREAD

**Issue by heyazoo1007** [heyazoo1007/accountbook#12]
## 📌  Feature Issue

한달/1년 동안의 지출내역을 카테고리별로 분류하는 기능입니다.
로그인한 사용자가 사용할 수 있습니다.
계정주만 사용할 수 있습니다. 

## 📝  To-do

- [x] 매달 1일에 다음 정보를 저장하는 기능 구현
    - [x] 지난달 총 지출 금액 
    - [x] 지난달 카테고리별 총 금액
- [x] 카테고리별로 금액 합산해서 조회하는 기능 구현
    - [x] 지난 달 조회(aggregation 테이블이용)
    - [x] 이번 달 조회
- [x] 1년 총 지출내역 카테고리별로 조회 기능 구현
- [x] 서비스 테스트 구현
