### ISSUE TITLE
[Deploy] Github Actions, AWS S3, AWS CodeDeploy로 CI/CD 구축하기

### ISSUE THREAD

**Issue by heyazoo1007** [heyazoo1007/accountbook#27]
## 📌  Feature Issue

개인 프로젝트를 AWS EC2에 자동 테스트/빌드 및 배포를 할 수 있는 시스템 구축을 연습하는 것 입니다. 

## 📝  To-do

- [ ] AppSpec.yml 작성
- [ ] stop.sh, start.sh 작성
- [ ] deploy.yaml 작성
